spring:
  cloud:
    stream:
      function:
        definition: processDropoffRideAverages
      bindings:
        processDropoffRideAverages-out-0:
          destination: taxi/nyc/v1/stats/dropoff/avg
        processDropoffRideAverages-in-0:
          destination: taxiUpdateQueue
      solace:
        bindings:
          processDropoffRideAverages-in-0:
            consumer:
              queueAdditionalSubscriptions: 'taxi/nyc/v1/dropoff/>'
solace:
  java:
    host: 'mr-d8f4yze27kt.messaging.solace.cloud:55555'
    msgVpn: cto-demo-virginia-azure
    clientUsername: live-stream-client
    clientPassword: solaceLive
logging:
  level:
    root: info
    org:
      springframework: info
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'

